version: '3'
services:

  # PHP Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    networks:
      - app-network

  # Vue Service
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - dist-volume:/app/dist
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7.16
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: 'comment'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3307:3306"
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dist-volume:
